// File generated by the FlutterFire CLI.
// Ignore issues from pub uploader.
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_private_typedef_functions

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy_nsz-bvLYsoY_hREgYxKNxyXSxNuLXY',
    appId: '1:371374410914:android:bb1b1be7f0eee1ba1f9bfb',
    messagingSenderId: '371374410914',
    projectId: 'omnicalendar-674eb',
    storageBucket: 'omnicalendar-674eb.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy_nsz-bvLYsoY_hREgYxKNxyXSxNuLXY',
    appId: '1:371374410914:web:placeholder',
    messagingSenderId: '371374410914',
    projectId: 'omnicalendar-674eb',
    authDomain: 'omnicalendar-674eb.firebaseapp.com',
    storageBucket: 'omnicalendar-674eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy_nsz-bvLYsoY_hREgYxKNxyXSxNuLXY',
    appId: '1:371374410914:ios:placeholder',
    messagingSenderId: '371374410914',
    projectId: 'omnicalendar-674eb',
    storageBucket: 'omnicalendar-674eb.firebasestorage.app',
    iosBundleId: 'com.example.flutterTesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy_nsz-bvLYsoY_hREgYxKNxyXSxNuLXY',
    appId: '1:371374410914:macos:placeholder',
    messagingSenderId: '371374410914',
    projectId: 'omnicalendar-674eb',
    storageBucket: 'omnicalendar-674eb.firebasestorage.app',
    iosBundleId: 'com.example.flutterTesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy_nsz-bvLYsoY_hREgYxKNxyXSxNuLXY',
    appId: '1:371374410914:windows:placeholder',
    messagingSenderId: '371374410914',
    projectId: 'omnicalendar-674eb',
    authDomain: 'omnicalendar-674eb.firebaseapp.com',
    storageBucket: 'omnicalendar-674eb.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBy_nsz-bvLYsoY_hREgYxKNxyXSxNuLXY',
    appId: '1:371374410914:linux:placeholder',
    messagingSenderId: '371374410914',
    projectId: 'omnicalendar-674eb',
    authDomain: 'omnicalendar-674eb.firebaseapp.com',
    storageBucket: 'omnicalendar-674eb.firebasestorage.app',
  );
}
